dependencies {
    /**
     * Type-safe model accessors is unavailable because this is script plugin that generated by apply(from = {gradle.kts})
     * Refer to documentation
     * @see https://docs.gradle.org/current/userguide/kotlin_dsl.html#type-safe-accessors
     */

    "implementation"(Dependencies.AndroidX.SUPPORT_LEGACY)
    "implementation"(Dependencies.AndroidX.APPCOMPAT)
    "implementation"(Dependencies.AndroidX.CONSTRAINT_LAYOUT)
    "implementation"(Dependencies.Google.MATERIAL)
    "testImplementation"(Dependencies.Test.JUNIT)
    "testImplementation"(Dependencies.Test.MOCKITO)
    "testImplementation"(Dependencies.Test.MOCKITO_INLINE)
    "testImplementation"(Dependencies.Test.MOCKITO_KOTLIN)
    "androidTestImplementation"(Dependencies.AndroidTest.JUNIT)
    "androidTestImplementation"(Dependencies.AndroidTest.ESPRESSO)
    "implementation"(Dependencies.KTX_CORE)
    "implementation"(Dependencies.KTX_ACTIVITY)
    "implementation"(Dependencies.KTX_FRAGMENT)
    "implementation"(Dependencies.Navigation.UI)
    "implementation"(Dependencies.Navigation.FRAGMENT_KTX)
    "implementation"(Dependencies.Navigation.DYNAMIC_FEATURE)
    "implementation"(Dependencies.COIL)
    "implementation"(Dependencies.Lifecycle.VIEWMODEL_KTX)
    "implementation"(Dependencies.Lifecycle.COMMON)
    "implementation"(Dependencies.DaggerHilt.ANDROID)
    "kapt"(Dependencies.DaggerHilt.COMPILER)
    "kapt"(Dependencies.Hilt.COMPILER)
    "implementation"(Dependencies.FlowBinding.ANDROID)
    "implementation"(Dependencies.FlowBinding.APPCOMPAT)
    "implementation"(Dependencies.TIMBER)
    "implementation"("com.google.android.play:core:1.8.3")
    "implementation"("com.google.android.play:core-ktx:1.8.1")
}

configurations {
    "implementation" {
        resolutionStrategy.failOnVersionConflict()
    }
}